Fix gradient checkpointing
- delete_gate_mask is a tensor with `requires_grad=True`, so it must be passed as a positional arg to work with gradient checkpointing, according to this PR
  - https://github.com/huggingface/transformers/pull/38913
- Without this change, running with `batch_size_multiplier=8,` or `gradient_checkpointing=True` would cause the following error:
```
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```