Fix requirements.txt version mismatch
- Running `pip install -r requirements.txt` with `python@3.11.14` failed with the two errors below. The tensorflow error only appeared after fixing the matplotlib error.
  - 3.11.14 is the nearest version I could use to 3.11.8, the python version that appears to be used throughout this project
  - https://github.com/search?q=repo%3Ajkallini%2Fmrt5+3.11&type=code
- This change updates the requirements to the nearest higher versions that fix the errors
- https://github.com/matplotlib/matplotlib/blob/v3.8.4/pyproject.toml
- https://github.com/tensorflow/tensorflow/pull/95895
```
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 3), -r requirements.txt (line 4) and numpy==2.2.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==2.2.3
    accelerate 0.28.0 depends on numpy>=1.17
    datasets 2.18.0 depends on numpy>=1.17
    matplotlib 3.8.3 depends on numpy<2 and >=1.21

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```
```
INFO: pip is looking at multiple versions of tensorflow to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 1), -r requirements.txt (line 10), -r requirements.txt (line 3), -r requirements.txt (line 4), -r requirements.txt (line 7), -r requirements.txt (line 8), -r requirements.txt (line 9) and numpy==2.2.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested numpy==2.2.3
    accelerate 0.28.0 depends on numpy>=1.17
    datasets 2.18.0 depends on numpy>=1.17
    matplotlib 3.8.4 depends on numpy>=1.21
    pandas 2.2.3 depends on numpy>=1.23.2; python_version == "3.11"
    scipy 1.15.2 depends on numpy<2.5 and >=1.23.5
    seaborn 0.13.2 depends on numpy!=1.24.0 and >=1.20
    tensorflow 2.19.0 depends on numpy<2.2.0 and >=1.26.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```