Remove apex
- When running `python train.py --help` I hit the error below
- Removing apex fixed things. I think this could be because my mac doesn't have cuda
  - I needed to explicitly run `pip uninstall apex`
- https://stackoverflow.com/q/66610378/2421313
```
  File "~/git/mrt5/.venv/lib/python3.11/site-packages/transformers/trainer.py", line 172, in <module>
    from apex import amp
  File "~/git/mrt5/.venv/lib/python3.11/site-packages/apex/__init__.py", line 13, in <module>
    from pyramid.session import UnencryptedCookieSessionFactoryConfig
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig' from 'pyramid.session' (unknown location)
```