Fix error when creating MrT5Trainer
- The basic issue is that since the version of transformers pinned by requirements.txt (4.39.1) and now (4.57.1), a new arg was added to `Trainer.__init__` called `compute_loss_func` (added in 4.54.1). This new arg broke things because T5Trainer in trainer.py uses positional args instead of keyword args, so all of the positional args are now effectively off by one
- The fix was to switch from positional args to keyword args to prevent the off-by-one issue
- This fix is backwards compatible with 4.39.1
- This issue is also mentioned in https://github.com/jkallini/mrt5/issues/1
- https://github.com/huggingface/transformers/commit/6ba31a8
- https://github.com/huggingface/transformers/pull/34198
```
File /opt/homebrew/Cellar/jupyterlab/4.4.5/libexec/lib/python3.13/site-packages/transformers/trainer.py:647, in Trainer.__init__(self, model, args, data_collator, train_dataset, eval_dataset, processing_class, model_init, compute_loss_func, compute_metrics, callbacks, optimizers, optimizer_cls_and_kwargs, preprocess_logits_for_metrics)
    645 self.compute_metrics = compute_metrics
    646 self.preprocess_logits_for_metrics = preprocess_logits_for_metrics
--> 647 self.optimizer, self.lr_scheduler = optimizers
    648 self.optimizer_cls_and_kwargs = optimizer_cls_and_kwargs
    649 if self.optimizer_cls_and_kwargs is not None and self.optimizer is not None:

TypeError: cannot unpack non-iterable NoneType object
```